export const ActionTypes = {
  INIT: "init",
  NOTIFY: "notify",
  START_EXPLORING: "startExploring",
  START_TRADE_TOKENS: "startTradeTokens",
  START_BUILD_FEATURE: "startBuildFeature",
  START_RECRUIT_UNITS: "startRecruitUnits",
  EXPLORE_ATTEMPT: "exploreAttempt",
  EXPLORE_FAILURE: "exploreFailure",
  EXPLORE_SUCCESS: "exploreSuccess",
  RESOLVE_NATURAL_FORMATION: "resolveNaturalFormation",
  RESOLVE_REMNANT: "resolveRemnant",
  UPDATE_TOKENS: "updateTokens",
  ENTER_COMBAT: "enterCombat",
  ADD_UNITS: "addUnits",
  THIEVES_TARGET_THE_HOLD: "thievesTargetTheHold",
} as const;
